name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    env:
      REACT_APP_API_KEY: "49312e5ae28f46bb9acf6b2bb2614291"
    runs-on: ubuntu-20.04
    steps:
      - name: CheckoutğŸ¯
        uses: actions/checkout@v2

      - name: Set up Node.js âš™ï¸
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies ğŸ“¦
        run: yarn install

      - name: Run the projectğŸ’¨
        run: yarn start

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress runğŸ’¨
        uses: cypress-io/github-action@v4
        with:
          build: yarn build
          start: yarn start
