name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: CheckoutğŸ¯
        uses: actions/checkout@v2

      - name: Run the projectğŸ’¨
        run: yarn start
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress runğŸ’¨
        uses: cypress-io/github-action@v4
        with:
          build: yarn build
          start: yarn start
