name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    env:
      REACT_APP_API_KEY: ${{secrets.APIKEY}}
    runs-on: ubuntu-20.04
    steps:
      - name: CheckoutðŸŽ¯
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress runðŸ’¨
        uses: cypress-io/github-action@v4
        with:
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
